# Generated by Django 2.2.1 on 2019-06-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=255)),
                ('parent_slug', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ports',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orig_code', models.CharField(max_length=55)),
                ('dest_code', models.CharField(max_length=55)),
                ('day', models.DateField()),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'prices',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=55)),
                ('name', models.CharField(max_length=255)),
                ('parent_slug', models.CharField(max_length=55)),
            ],
            options={
                'db_table': 'regions',
            },
        ),
    ]
